services:
  redis:
    image: redis:latest
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 5
    command: ['redis-server']
    ports:
      - 6379:6379
